language: node_js
node_js:
  - 10.8
services:
  - mongodb
install:
  - npm install
  - npm --prefix ./client install ./client
  - npm run build-production-test
cache:
  directories:
    - ~/.npm
    - ~/.cache
before_script:
  - node ./bin/www --silent &
script:
  - npm run cypress:run
