language: node_js
node_js:
  - 10.8
services:
  - mongodb
before_install:
  #clone encompass
  - "git clone https://github.com/DanielJKelly/encompass.git encompass"
  - "cd encompass"
  - "npm install"
  - "grunt serve-seed"
install:
  - npm ci
  - npm install
  - npm --prefix ./client install ./client
  - npm run build-production-test
cache:
  directories:
    - ~/.npm
    - ~/.cache
before_script:
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - node ./bin/www &
script:
  - npm run cypress:run
  #  ADD THIS TO PACKAGE>JSON CYPRESS SCRUPT
