language: node_js
node_js:
  - 10.8
services:
  - mongodb
install:
  - npm ci
  - npm install
  - npm --prefix ./client install ./client
  - npm run build-production-test
cache:
  directories:
    - ~/.npm
    - ~/.cache
before_script:
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - node ./bin/www &
script:
  - npm run cypress:run --record --key 103dfac6-8e4d-4672-adf9-b661fb7738da
  #  ADD THIS TO PACKAGE>JSON CYPRESS SCRUPT
